---
title: "NL Colonies Map"
author: "Gretchen McPhail and Sydney Collins"
date: "2023-06-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Load Packages}
rm(list=ls())
library(tidyverse)
library(sf)
library(cowplot)
library(legendMap)
library(rlang)
require(gridExtra)
require(raster)
library(maps)
library(ggforce)
require(grid)
library(rgdal)

load("data/Canada.Rda")

IBA <- fortify(readOGR("data/IBA_NFLD.kml"))
```

```{r Map with Inset}
CSM <- as.data.frame(cbind(46.831944, -54.165833))
BC <- as.data.frame(cbind(48.130278, -52.801389))
Funk <- as.data.frame(cbind(49.756667, -53.183889))
BA <- as.data.frame(cbind(48.495, -64.165))
AT <- as.data.frame(cbind(49.2, -61.6))
GBR <- as.data.frame(cbind(47.8, -61.0))
MG <- as.data.frame(cbind(47.448333, -61.752222))
LAWN <- as.data.frame(cbind(46.869038, -55.617111))
HARE <- as.data.frame(cbind(51.257219, -55.955525))
WB <- as.data.frame(cbind(47.268642, -52.787973))
WI <- as.data.frame(cbind(49.542837, -53.889413))

main_map <- ggplot() +
  xlab("Longitude") + 
  ylab("Latitude") +
  coord_map(xlim = c(-66, -48), ylim = c(43, 54.5))+
  geom_polygon(data = Canada, aes(x = long, y = lat, group = group), colour = "black", fill = "lightgrey") +
  geom_point(data = MG, aes(y = V1, x = V2), size = 3) +
  geom_point(data = CSM, aes(y = V1, x = V2), size = 3) +
  geom_point(data = BC, aes(y = V1, x = V2), size = 3) +
  geom_point(data = Funk, aes(y = V1, x = V2), size = 3) +
  geom_point(data = LAWN, aes(y = V1, x = V2), size = 3) +
  geom_point(data = HARE, aes(y = V1, x = V2), size = 3) +
  geom_point(data = WB, aes(y = V1, x = V2), size = 3) +
  annotate("text", cex = 2.5, x = c(-61.1, -53, -56, -62.8, -57.5, -64, -51.38, -52.08, -55.5, -54.9, -51.68), y = c(47.8, 46.5, 48.5, 45.2, 52.5, 51.5, 48.3, 49.9, 46.7, 51.27, 47.3), label= c("Îles-de-la-Madeleine", "Cape St. Mary's", "Newfoundland", "Nova Scotia", "Labrador", "Québec", "Baccalieu Island","Funk Island", "Lawn Islands", "Hare Bay", "Witless Bay")) +
  theme(panel.background = element_rect(fill = 'white', colour = "black"), axis.text.x = element_text(size = 10), axis.text.y = element_text(size = 10)) +
  scale_bar(lon = -53.5, lat = 43, distance_lon = 200, distance_lat = 50, distance_legend = 100, dist_unit = "km", orientation = F) +
  scale_bar(lon = -67, lat = 40, distance_lon = 200, distance_lat = 50, distance_legend = 100, dist_unit = "km", orientation = T, arrow_length = 80, arrow_distance = 1500)
main_map

mainmap2 <- ggplot() +
  xlab("Longitude") + 
  ylab("Latitude") +
  coord_map(xlim = c(-62, -51), ylim = c(45.5, 52.5)) +
  geom_polygon(data = Canada, aes(x = long, y = lat, group = group), colour = "black", fill = "lightgrey") +
  geom_polygon(data = IBA, aes(x = long, y = lat, group = group), fill = "red") +
  geom_point(aes(y = 46.831944, x = -54.165833), size = 2) +
  geom_point(aes(y = 48.130278, x = -52.801389), size = 2) +
  geom_point(aes(y = 49.756667, x = -53.183889), size = 2) +
  geom_point(aes(y = 51.257219, x = -55.955525), size = 2) +
  geom_point(aes(y = 47.268642, x = -52.787973), size = 2) +
  geom_point(aes(y = 46.869038, x = -55.617111), size = 2) +
  annotate("text", cex = 2.5, x = c(-61.1, -54.7, -56, -62, -62, -57.5, -61, -51.8, -52.4, -52.05, -56.35, -55.4, -53.4, -53.4), y = c(47.8, 46.7, 48.5, 45.5, 45.35, 52.2, 51, 48.13, 49.76, 47.27, 46.8, 51.25, 47.35, 47.25), label= c("Îles-de-la-Madeleine", "Cape St. Mary's", "Newfoundland", "Nova", "Scotia", "Labrador", "Québec", "Baccalieu Island","Funk Island", "Witless Bay", "Lawn Islands", "Hare Bay", "Avalon", "Peninsula")) +
  theme(panel.background = element_rect(fill = 'white', colour = "black"), axis.text.x = element_text(size = 10), axis.text.y = element_text(size = 10)) +
  scale_bar(lon = -54, lat = 45.5, distance_lon = 100, distance_lat = 30, distance_legend = 50, dist_unit = "km", orientation = F) +
  scale_bar(lon = -63.5, lat = 40, distance_lon = 200, distance_lat = 50, distance_legend = 100, dist_unit = "km", orientation = T, arrow_length = 80, arrow_distance = 1300)
mainmap2

world_map <- map_data("world")

ph1 <- getData("GADM", country = "CAN", level = 1)

pol <- data.frame(xmin = -66, xmax = -48, ymin = 43, ymax = 54.5)

p2 <- ggplot() +
  geom_map(data = world_map, map = world_map, aes(long, lat, map_id = region), color = "black", fill = "lightgray", size = 0.1) +
  geom_rect(data = pol, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red", size = 1, linetype = 1) +
  theme(panel.background = element_rect(fill = 'white', colour = 'black'), axis.text.x = element_blank(), axis.text.y = element_blank(), axis.ticks = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), plot.margin = unit(c(-1,-1,-1,-1),"mm"))


jpeg(filename = "figures/Figure1_Full_map.jpeg", units = "mm", width = 180, height = 150, res = 300)
grid.newpage()
v1<-viewport(width = 1, height = 1, x = 0.5, y = 0.5) #plot area for the main map
v2<-viewport(width = 0.25, height = 0.18, x = 0.78, y = 0.87) #plot area for the inset map
print(mainmap2,vp=v1) 
print(p2,vp=v2)
dev.off()

```

```{r}
colonies_species <- read.csv("data/atlantic-bird-colonies.csv")

colonies <- summaryBy(MAX_COUNT ~ COLNAME + COL_LATDEC + COL_LONDEC, data = colonies_species, FUN = sum) %>%
  filter(MAX_COUNT.sum > 10000) %>%
  filter(COL_LONDEC > -60) %>%
  filter(COL_LATDEC < 50)

ggplot() +
  xlab("Longitude") + 
  ylab("Latitude") +
  coord_map(xlim = c(-66, -48), ylim = c(43, 54.5))+
  geom_polygon(data = Canada, aes(x = long, y = lat, group = group), colour = "black", fill = "lightgrey") + 
  geom_point(data = colonies, aes(x = COL_LONDEC, y = COL_LATDEC)) +
  theme(panel.background = element_rect(fill = 'white', colour = "black"), axis.text.x = element_text(size = 10), axis.text.y = element_text(size = 10))
```

```{r}
ggplot() +
  xlab("Longitude") + 
  ylab("Latitude") +
  coord_map(xlim = c(-66, -48), ylim = c(43, 54.5))+
  geom_polygon(data = Canada, aes(x = long, y = lat, group = group), colour = "black", fill = "lightgrey") + 
  geom_point(data = colonies_species %>% filter(SPECIES_CO == "RAZO"), aes(x = COL_LONDEC, y = COL_LATDEC, size = MAX_COUNT)) +
  theme(panel.background = element_rect(fill = 'white', colour = "black"), axis.text.x = element_text(size = 10), axis.text.y = element_text(size = 10))
```

