---
title: "NFLD_HPAI_Data_Cleanup"
author: "Gretchen McPhail and Sydney Collins"
date: "2023-06-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Load Packages}
rm(list=ls())
library(tidyverse)
library(doBy)
library(lubridate)
```

```{r download and organize data}
#create dataset of just seabirds
hpai <- read.csv("data/2023-06-22_HPAI_Mortality_Tracker - Newfoundland.csv", na = "NA") %>%
  select(UniqueID, SiteName, Year, Month, Day, DateObserved, Lat, Long, SpeciesAlphaCode, GroupAs, Individual_HPAIVstatus, AgeClass, LandWater, Colony_Y_N,  IFcolony_complete_partial_survey, TotalObserved) %>%
  dplyr::rename(Species = SpeciesAlphaCode, Date = DateObserved, Total = TotalObserved) %>%
  mutate(Date = as.Date(Date)) %>%
  mutate(TotalCat = ifelse(Total > 1000, "1000+", ifelse(Total > 500, "500-1000", ifelse(Total > 100, "100-500", ifelse(Total > 50, "50-100", ifelse(Total > 10, "10-50", "1-10")))))) %>%
  filter(GroupAs %>% str_detect("seabirds")) %>%
  filter(Individual_HPAIVstatus == "positive" | is.na(Individual_HPAIVstatus)) %>%
  select(-GroupAs) %>%
  arrange(Date) %>%
  mutate(Lat = round(Lat, 1)) %>%
  mutate(Long = round(Long, 1))

#Change all 'unknown' species to other
top4species <- c("COMU", "NOGA", "ATPU", "BLKI")
hpai$Top4 <- sapply(strsplit(hpai$Species, ',,\\s*'), function(x) {  x[!x %in% top4species ] <- 'Other'
  toString(x)})

summary(as.factor(hpai$Species))

#Make Newfoundland polygon
world_map <- map_data("world")
Newfoundland <- subset(world_map, world_map$subregion == "Newfoundland")
Canada <- subset(world_map, world_map$region == "Canada")

#save the data files
save(hpai, file = "data/hpai.Rda")
save(Canada, file = "data/Canada.Rda")
```